### ISSUE TITLE
Minor (?) issue with PyInstaller

### ISSUE THREAD

**Issue by exvito** [pybee/rubicon-objc#10] opened 2016-09-26 00:26 UTC
Hello, thanks for sharing the project. I particularly like the light approach at interfacing with ObjC libraries when compared with PyObjC.

I was playing around with it and successfully interfaced with the Address Book in my Mac: I created a simple script to dump its entries to stdout.

Then I went further I tried to package it with PyInstaller -- unfortunatelly, the frozen version failed to run.

I found the culprit to be the following line, in objc.py:

```
objc = cdll.LoadLibrary(util.find_library(b'objc'))                                       
```

On my environment, running Mac OS X 10.9.5, Python 3.5.2, I found out that `ctypes.util.find_library` returns `None` when given bytes but works when given text:

```
Python 3.5.2 (default, Jul 16 2016, 11:57:33) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes import util
>>> util.find_library(b'objc')
>>> repr(util.find_library(b'objc'))
'None'
>>> util.find_library('objc')
'/usr/lib/libobjc.dylib'
```

After changing the aforementioned line in objc.py to use text instead of bytes -- that is `'objc'` instead of `b'objc'` -- the PyInstaller frozen version ran successfully.

Of course, the mystery is explaining how on earth the non-frozen script runs -- I double checked that both were running under the same Python 3.5.2 virtual env.

I took a look at the ctypes documentation and I couldn't find clear information on whether the name argument to `ctypes.util.find_library` should be binary or text.

So, the questions are:
* Why did you use bytes instead of text for `find_library`?
* Does the code above behave differently in your environment?

Thanks again.
Regards.

**Comment by freakboy3742** [comment] 2016-09-26 01:28
This *is* odd. I can confirm that if I fire up a shell, I get the same behavior you describe.

I can only assume that there's some odd interaction going on with `from __future__` at some point, because rubicon definitely works for me at runtime. 

Interestingly, the code loads CoreFoundation *without* the `b` prefix. 

I've just pushed update 8919d882f; can you confirm if this corrects the problem for you?

**Comment by exvito** [comment] 2016-09-26 13:52
Thanks for the quick update.

I do confirm that with 8919d882f3b710fa8927b3d41e1ee1369769ef19 my test script runs successfully both in the "regular" non-frozen mode and after PyInstaller freezing.

Some additional information and tests:

My library loading + setup code is as follows:
```
for name in ('Foundation', 'AddressBook'):
    lib_path = ctypes.util.find_library(name)                                         
    libs[name] = ctypes.cdll.LoadLibrary(lib_path)

ABAddressBook = objc.ObjCClass('ABAddressBook')
```

Note the use text strings for both libraries. If I use binary `b'Foundation'` and `b'AddressBook'` the for loop completes, but instantiating the `ABAddressBook` class fails:
```
Traceback (most recent call last):
  File "x.py", line 16, in <module>
    ABAddressBook = objc.ObjCClass('ABAddressBook')
  File ".../rubicon/github.com/rubicon-objc/rubicon/objc/objc.py", line 1117, in __new__
    raise NameError("ObjC Class '%s' couldn't be found." % class_name_or_ptr)
NameError: ObjC Class 'ABAddressBook' couldn't be found.
```

This seems consistent with my previous observation where `ctypes.util.find_library` failed to return useful information when fed a binary as in `name=b'objc'`.

**Comment by freakboy3742** [comment] 2016-09-27 02:38
Ok - closing this as resolved on the basis of your feedback; it's been rolled into v0.2.3. That release also strips out the last of the Python 2 compatibility code, so the ambiguity shouldn't be a factor any more.

**Closed by freakboy3742** 2016-09-27 02:38 UTC

**Comment by exvito** [comment] 2016-09-28 02:18
Again, thanks for the quick response.
